### ISSUE TITLE
Bitmap image instead a vector in folder icons

### ISSUE THREAD

**Issue by SmartFinn** [gusbemacbe/suru-plus-alpha#6]
A few folder icons content bitmap image instead of a vector:

```
$ cd places/scalable
$ LC_ALL=C egrep -rl --include='*.svg' -e '<image[ ]' . | grep blue
./folder-blue-visiting.svg
./folder-blue-wifi.svg
./folder-blue-wine.svg
./folder-blue-yandex-disk.svg
./user-blue-home.svg
```

No need fixing other colors, they will be overwrited.

**Comment by gusbemacbe** [comment]
Sorry for my absence, I was configuring and installing Android on my brother's HDD because he has no knowledge of Linux.  

But do I need still to replace RGB for HEX?

**Comment by SmartFinn** [comment]
> But do I need still to replace RGB for HEX?

Before do it need to fix these icons. The icons have neither HEX nor RGB colors.

**Comment by gusbemacbe** [comment]
@SmartFinn 

Hi, ready, I replaced all RGB for HEX.

I also fixed all bitmap images, it was Gravit Designer bug. 

I removed all Gravit base64 codes.

**Comment by gusbemacbe** [comment]
Sorry again for messing two icons! I have just fixed again.

**Comment by SmartFinn** [comment]
I see two icons with same content:

- places/16/folder-apps.svg
- places/16/folder-app.svg

and

- places/scalable/folder-apps.svg
- places/scalable/folder-app.svg

Is folder-app.svg a typo? Can I delete it or have to create symlinks?

**Comment by gusbemacbe** [comment]
Yes, you can. Folder-app and folder-apps are the same thing.

**Comment by gusbemacbe** [comment]
```shell
COLORS=(
	# [0] - primary color
	# [1] - secondary color
	# [2] - color of symbol
	# [3] - color of panel
	#
	# | name   | [0]   | [1]   | [2]   | [3]   |
	# |--------|-------|-------|-------|-------|
	[blue]="    #37A6E6 #1463A5 #FFFFFF #333333"
	# add your colors below
	[black]="   #333333 #1A1A1A #FFFFFF #000000"
	[bluegrey]="#78909C #455A64 #CFD8DC #333333"
	[brown]="   #AE8E6C #957552 #FFFFFF #333333"
	[cyan]="    #31C6B7 #2B898F #FFFFFF #333333"
	[green]="   #76C22B #28851E #FFFFFF #333333"
	[grey]="    #999999 #666666 #FFFFFF #333333"
	[magenta]=" #F74761 #C61B34 #FFFFFF #333333"
	[orange]="  #fb7c38 #f34f17 #FFFFFF #333333"
	[red]="     #F22C42 #BC1938 #FFFFFF #333333"
	[teal]="    #26A69A #00796B #FFFFFF #333333"
	[violet]="  #8F76E4 #7839B7 #FFFFFF #333333"
	[yellow]="  #fdc92b #eab305 #333333 #333333"
	[custom]="  #value_light #value_dark #323232 #e4e4e4"
)
```

**Comment by gusbemacbe** [comment]
Ready
